Repository MPAS-Dev/MPAS-Model, pull requests merged in 2023-07, with the labels that each got.

#1099 Fix OpenMP error in deallocation of rthdynten without certain cumulus schemes
  src/core_atmosphere/Registry.xml
  src/core_atmosphere/dynamics/mpas_atm_time_integration.F
Labels: Atmosphere, bug fix

#1094 Add mpas_modify_att() subroutines to mpas_attlist
  src/core_test/mpas_test_core_field_tests.F
  src/framework/mpas_attlist.F
Labels: Atmosphere

#1103 Update fortprintf to support Fortran 2003 linebreaks
  src/tools/registry/fortprintf.c
Labels: Framework, clean-up

#1105 Remove the azure-pipelines.yml file, as it is no longer used
  azure-pipelines.yml
Labels: Framework, clean-up
