Repository MPAS-Dev/MPAS-Model, pull requests merged in 2024-01, with the labels that each got.

#1129 Add build target 'intel' for the Intel oneAPI compilers
  Makefile
Labels: Framework

#1132 Add new mpas_stream_inquiry infrastructure module for querying contents of streams files
  src/core_test/Makefile
  src/core_test/Registry.xml
  src/core_test/mpas_test_core.F
  src/core_test/mpas_test_core_stream_inquiry.F
  src/driver/mpas_subdriver.F
  src/framework/Makefile
  src/framework/mpas_derived_types.F
  src/framework/mpas_domain_types.inc
  src/framework/mpas_stream_inquiry.F
  src/framework/mpas_stream_inquiry_types.inc
  src/framework/stream_inquiry.c
Labels: feature, Framework

#1135 Fix halo exchange unit tests in the test core
  src/core_test/mpas_test_core_halo_exch.F
Labels: bug fix

#1133 Add `streamInfo` argument to `setup_packages` and `get_mesh_stream` interfaces for all cores
  src/core_atmosphere/mpas_atm_core_interface.F
  src/core_init_atmosphere/mpas_init_atm_core_interface.F
  src/core_landice/mode_forward/mpas_li_core_interface.F
  src/core_ocean/driver/mpas_ocn_core_interface.F
  src/core_seaice/model_forward/mpas_seaice_core_interface.F
  src/core_sw/mpas_sw_core_interface.F
  src/core_test/mpas_test_core_interface.F
  src/driver/mpas_subdriver.F
  src/framework/mpas_core_types.inc
Labels: feature

#1137 Introduce "invariant stream" capability to MPAS-Atmosphere
  src/core_atmosphere/Makefile
  src/core_atmosphere/Registry.xml
  src/core_atmosphere/mpas_atm_core.F
  src/core_atmosphere/mpas_atm_core_interface.F
Labels: feature, Atmosphere
